// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomTextOnTitleScreen","status":true,"description":"Ver.2015-11-06-0008. Displays a custom text on title screen.\r\n<Ellye Title Text>","parameters":{"Text":"Navegar: SETAS Confirmar: ENTER","h_align":"2","v_align":"2","X Offset":"0","Y Offset":"0","Outline Color":"#000000","Outline Width":"3","Font Size":"23","Text Color":"#FFFFFF"}}
];
